# Generated by Django 3.2.4 on 2021-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210606_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('ram', 'ram'), ('rom', 'rom')], max_length=200),
        ),
    ]
